version: "3"

tasks:
  run:
    deps: [build]
    cmds:
      - ./raytracer
    generates:
      - image.png
  view:
    cmds:
      - open -a Preview image.png
  clean:
    cmds:
      - touch image.png
      - rm image.png
  build:
    cmds:
      - go build -o raytracer ./cmd
  install-deps:
    cmds:
      - brew install sdl2{,_image,_mixer,_ttf,_gfx} pkg-config
      - go mod download
